### ISSUE TITLE
stuck inside the amogus easter egg

### ISSUE THREAD

**Issue by Quantaviousdingleberry420** [aeolus-1/triangleGame.github.io#27]
<img width="437" alt="Screen Shot 2022-04-20 at 12 17 20 pm" src="https://user-images.githubusercontent.com/104042540/164134042-0764e970-2d95-4c38-8956-29b3a62d2c42.png">
plz fix

**Comment by LX8369** [comment]
thats pretty sus

**Comment by daquaviousbingleton1** [comment]
![amog](https://user-images.githubusercontent.com/104043026/164140465-953126a8-bf88-4328-a0db-20fe1597a3af.jpeg)

**Comment by Quantaviousdingleberry420** [comment]
amoogus

**Comment by aeolus-1** [comment]
you used the ghost cheat im not dumb dumb
