### ISSUE TITLE
Balls stacking up - plz reply if this issue is found

### ISSUE THREAD

**Issue by Quantaviousdingleberry420** [aeolus-1/triangleGame.github.io#65]
there are a few areas in the game where the balls stack up, just under the 3 holes in the floor is where they do that the most when you jump on skinny platforms which makes it so that you get bombarded

**Comment by aeolus-1** [comment]
I am aware of this
this is a large issue
working on it imediently

**Comment by aeolus-1** [comment]
fixed
balls dont collide with each other now

**Comment by Quantaviousdingleberry420** [comment]
working now 👍
