### ISSUE TITLE
Jumping not working properly on multiplayer

### ISSUE THREAD

**Issue by Quantaviousdingleberry420** [aeolus-1/triangleGame.github.io#70]
slightly less just force, also avatar will move when jumping while being still

**Comment by LX8369** [comment]
yeah i have noticed that

**Comment by aeolus-1** [comment]
me too 
might have somehting todo with walljump

**Comment by LX8369** [comment]
yeah it seems when offline walljump is set to 0 but online its always set to 1

**Comment by aeolus-1** [comment]
Ive changed it so walljumps are the same a normal jumps
mostly the same
stronger walljumps now
